{% set version = "2.0.11" %}
{% set build_number = "0" %}

{% set hdf5_version = os.environ.get('HDF5_VERSION', '1.8.17|1.8.17.*').replace('"','')|string %}
{% set build_string = "py{}_hdf5{}_{}".format(environ.get('CONDA_PY', ''), hdf5_version.split('|')[0], build_number) %}

package:
  name: bob.io.base
  version: {{ version }}

source:
  fn: bob.io.base-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.io.base/bob.io.base-{{ version }}.zip
  md5: e1ed944724ca98f62f51691d0ed29987

build:
  number: {{ build_number }}
  string: {{ build_string }}
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - hdf5 {{ hdf5_version }}
  - cmake
  - pkg-config
  - boost 1.61.*

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - hdf5 {{ hdf5_version }}
  - boost 1.61.*

test:
  imports:
  - bob
  - bob.io
  - bob.io.base

  commands:
    - nosetests -sv bob.io.base

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Basic IO for Bob

extra:
  recipe-maintainers:
  - 183amir
